local options = {
	backup = false,
	completeopt = { "menuone", "noselect" },
	conceallevel = 0,
	clipboard = "unnamedplus",
	cmdheight = 2,
	cursorline = true,
	expandtab = true,
	foldcolumn = "0",
	-- foldmethod = "expr",
	foldenable = true,
	-- foldexpr = "nvim_treesitter#foldexpr()",
	foldlevel = 99,
	foldlevelstart = 99,
	fileencoding = "utf-8",
	fillchars = [[eob: ,fold: ,foldopen:,foldsep: ,foldclose:]],
	hlsearch = true,
	ignorecase = true,
	laststatus = 3,
	mouse = "a",
	mousemoveevent = true,
	number = true,
	pumheight = 10,
	relativenumber = true,
	scrolloff = 8,
	shiftwidth = 2,
	showtabline = 2,
	signcolumn = "yes:1",
	smartcase = true,
	--[[ smartindent = true, ]]
	splitbelow = true,
	splitright = true,
	swapfile = false,
	syntax = "on",
	undofile = true,
	updatetime = 300,
	termguicolors = true,
	tabstop = 2,
	wrap = true,
}

for k, v in pairs(options) do
	vim.opt[k] = v
end
